version: '3'

services:
#    sales_manager:
#        container_name: sales_manager
#        build: sales_manager/.
#        volumes:
#            - .:/app
#        depends_on:
#            - mysql_db

    mysql_db:
        container_name: mysql_db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysecurepass
            MYSQL_DATABASE: mydb
        ports:
            - '3306:3306'
        volumes:
            - ./database:/var/lib/mysql
