version: '3'

services:
    mysql_db:
        container_name: mysql_db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - '3306:3306'
        volumes:
            - ./database:/var/lib/mysql
